### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by autronix** [yegor256/requs#103]
I have gone through the documentation and definitely see a place for it in some of my projects.

I'm curious to know whether this project is still alive given that the demo site is online and there hasn't seemingly been any updates in a while.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@autronix thanks for your interest. The project is alive, although we're not using it in any projects of ours. Mostly because in practice, on small projects, it's more convenient to work with plain text English. We should definitely get back to this idea again, but in some time. If you're interested to use Requs in your project, I will try to help you!

**Comment by autronix** [comment]
@yegor256 Thanks for developing the concept, I find the idea of properly structuring the development requirements very appealing since it otherwise tends to be messy - I'll be attempting to apply the concept on a project I'm currently working on. I'm glad to know this is still a work in progress.

**Comment by yegor256** [comment]
@autronix sure, please go ahead. I had some good results with it in one of our projects a few months ago. Take a look at this collection of specifications, for example: https://github.com/yegor256/thindeck/tree/0.5/src/main/requs

**Comment by autronix** [comment]
That's a great starting point, thanks for sharing!

**Comment by yegor256** [comment]
@autronix yes, it's alive!
